<a href="https://colab.research.google.com/github/Alfi-Lukmanul/Data-Mining/blob/main/Tugas_Akhir_Alfi_Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd
from sklearn import tree

In [13]:
#Membaca Dataset dari file ke pandas DataFrame
HeartDataset=pd.read_csv('heart.csv', header=0)

In [14]:
HeartDataset.head(5)

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [15]:
HeartDataset["target"] = pd.factorize(HeartDataset.target)[0]

In [16]:
print(HeartDataset)

     age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       0
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       0
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       0
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       0
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       0
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       1
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       1
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       1
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       1
302   57    0   1       130   236    0  ...      0      0.0      

In [17]:
HeartDataset = HeartDataset.to_numpy()
#Mengybah dataFrame ke arah Numpy

In [18]:
print(HeartDataset)

[[63.  1.  3. ...  0.  1.  0.]
 [37.  1.  2. ...  0.  2.  0.]
 [41.  0.  1. ...  0.  2.  0.]
 ...
 [68.  1.  0. ...  2.  3.  1.]
 [57.  1.  0. ...  1.  3.  1.]
 [57.  0.  1. ...  1.  2.  1.]]


In [57]:
#Membagi Dataset = > 60 Baris data untuk Data Testing, sisanya untuk Data Training
dataTraining = np.concatenate((HeartDataset[0:123,:], HeartDataset[153:273, :]),axis=0)
dataTesting = np.concatenate((HeartDataset[123:153,:], HeartDataset[273:303, :]),axis=0)

In [58]:
print(dataTraining)
len(dataTraining)

[[63.  1.  3. ...  0.  1.  0.]
 [37.  1.  2. ...  0.  2.  0.]
 [41.  0.  1. ...  0.  2.  0.]
 ...
 [46.  1.  0. ...  0.  3.  1.]
 [61.  1.  3. ...  2.  2.  1.]
 [67.  1.  0. ...  0.  2.  1.]]


243

In [59]:
print(dataTesting)
len(dataTesting)

[[5.40e+01 0.00e+00 2.00e+00 1.08e+02 2.67e+02 0.00e+00 0.00e+00 1.67e+02
  0.00e+00 0.00e+00 2.00e+00 0.00e+00 2.00e+00 0.00e+00]
 [3.90e+01 0.00e+00 2.00e+00 9.40e+01 1.99e+02 0.00e+00 1.00e+00 1.79e+02
  0.00e+00 0.00e+00 2.00e+00 0.00e+00 2.00e+00 0.00e+00]
 [3.40e+01 0.00e+00 1.00e+00 1.18e+02 2.10e+02 0.00e+00 1.00e+00 1.92e+02
  0.00e+00 7.00e-01 2.00e+00 0.00e+00 2.00e+00 0.00e+00]
 [4.70e+01 1.00e+00 0.00e+00 1.12e+02 2.04e+02 0.00e+00 1.00e+00 1.43e+02
  0.00e+00 1.00e-01 2.00e+00 0.00e+00 2.00e+00 0.00e+00]
 [6.70e+01 0.00e+00 2.00e+00 1.52e+02 2.77e+02 0.00e+00 1.00e+00 1.72e+02
  0.00e+00 0.00e+00 2.00e+00 1.00e+00 2.00e+00 0.00e+00]
 [5.20e+01 0.00e+00 2.00e+00 1.36e+02 1.96e+02 0.00e+00 0.00e+00 1.69e+02
  0.00e+00 1.00e-01 1.00e+00 0.00e+00 2.00e+00 0.00e+00]
 [7.40e+01 0.00e+00 1.00e+00 1.20e+02 2.69e+02 0.00e+00 0.00e+00 1.21e+02
  1.00e+00 2.00e-01 2.00e+00 1.00e+00 2.00e+00 0.00e+00]
 [5.40e+01 0.00e+00 2.00e+00 1.60e+02 2.01e+02 0.00e+00 1.00e+00 1.63e+02
  0.00e+0

60

In [60]:
#Memecah DAtaset ke input dan label
inputTraining = dataTraining[:, 0:13]
inputTesting = dataTesting[:, 0:13]
labelTraining = dataTraining[:, 13]
labelTesting = dataTesting[:, 13]
print(labelTraining)
len(labelTraining)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]


243

In [61]:
#Mendefinisikan Decision Tree Classifer
model =tree.DecisionTreeClassifier()

In [62]:
#Mentraining Model
model = model.fit(inputTraining, labelTraining)

In [63]:
#Memprediksi Input Data Testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Hasil Prediksi :  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1.
 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1.
 1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1.]


In [64]:
#Menghitung Akurasi
prediksiBenar = (hasilPrediksi==labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar : ", prediksiBenar, " data")
print("Prediksi Salah : ", prediksiSalah, " data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

Prediksi Benar :  39  data
Prediksi Salah :  21  data
Akurasi :  65.0 %
